### ISSUE TITLE
As user I want to pass a multi-word command line argument to hurry

### ISSUE THREAD

**Issue by chistyakov** [Telichkin/hurry#1]
e.g.

I have such hurry.json:
```
{
    "functests <args>": "docker-compose exec functests pytest <args>",
}
```
and want to pass pass few arguments to pytest with something like this:

```
hurry functests -k mytest -vv -s
```

**Comment by Telichkin** [comment]
Is it okay, if you should pass these parameters in quotes?
```
hurry functests "-k mytest -vv -s"
```

**Comment by chistyakov** [comment]
Sounds ok for me

**Comment by Telichkin** [comment]
@chistyakov support added. Install latest version of hurry with `pip3 install hurry`. `hurry-script` is already unsupported
